---
title: "AMU workflow example"
author: "Nash"
date: "2026-06-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(epiDisplay)
library(ggplot2)
library(dplyr)
library(tidyr)
library(scales)
library(reshape)
library(reshape2)
library(data.table)
library(magrittr)
library(lubridate)
library(httr)
library(RColorBrewer)
library(tools)
library(stats)
library(janitor)

```


```{r}

###Import data

qamu<-read.csv("study farms dataset.csv")

#create a column for production day (age of birds)

qamu_age<-qamu%>%
  mutate(
    indiv_flock.date_on_form = as.Date(indiv_flock.date_on_form, format = "%m/%d/%Y"),
    flock_t.flock_loop_group.date_recieved = as.Date(flock_t.flock_loop_group.date_recieved, format = "%m/%d/%Y")
  ) %>%
  dplyr::mutate(flock_t.flock_loop_group.number_doc=case_when(flock_t.flock_loop_group.number_doc==408 & coversheet.farm_barcode=="AMR003484" & flock_t.flock_loop_group.date_recieved=="2024-07-17"~405,
                                                              TRUE~flock_t.flock_loop_group.number_doc))%>%
  
  group_by(Farm_ID, No_cycles) %>%
  complete(
    indiv_flock.date_on_form = seq(min(flock_t.flock_loop_group.date_recieved, na.rm = TRUE), 
                                   max(indiv_flock.date_on_form, na.rm = TRUE), 
                                   by = "day")
  ) %>%
  fill(Farm_ID, coversheet.farm_barcode, No_cycles, flock_t.flock_loop_group.date_recieved, 
       flock_t.flock_loop_group.number_doc, .direction = "down") %>%
  mutate(Production_day = as.numeric(indiv_flock.date_on_form - flock_t.flock_loop_group.date_recieved) + 1) %>%
  ungroup()%>%
filter(!is.na(flock_t.flock_loop_group.date_recieved)) %>% # Remove rows with missing DOC received date
  group_by(Farm_ID, No_cycles)%>%
   filter(Production_day > 0) %>%
  filter(Production_day<=56)%>%
  ungroup()

```


```{r}

###farms that used antibiotics

AMU<-qamu_age %>%
  mutate(AMU=ifelse(is.na(med_usage.name_of_antibiotics),"No","Yes"))
  
AMU1<-AMU%>%
  dplyr::select(coversheet.farm_barcode,Farm_cycle,production_cycles,AMU)%>%
  distinct()%>%
  group_by(production_cycles)%>%
  mutate(AMU = if ("Yes" %in% AMU) "Yes" else AMU) %>%
  ungroup()%>%
  distinct()%>%
  mutate(across(c(production_cycles,AMU),as.factor))%>%
  mutate(AMU=case_when(
    production_cycles==180~"No",
  TRUE~AMU))
  

write.csv(AMU1,"farm AMU.csv")
table(AMU1$AMU)


###Plot and save AMU farms

tiff(filename = "AMU use in production cycles.tiff", type = "cairo", units = "in", width = 16,height = 10, pointsize = 7, res = 400)

ggplot(AMU2, aes(x = AMU,y=percent_farms)) +
  geom_bar(stat = "identity", width = 0.1) +
  labs(x = "Antimicrobial Use (AMU)", y = "Proportion of production cycles") +
  theme_bw(base_size = 16)+
  scale_y_continuous(breaks = seq(0,70,10))+
  theme(axis.text.x = element_text(angle = 0, hjust = 1))+
    theme(
    axis.title = element_text(size = 22, face = "bold", colour = "black"),
    plot.title = element_text(size = 22,face = "bold"),
    axis.text = element_text(size = 22, face = "bold", color = "black", angle = 0),
    legend.title = element_text(size = 24,face = "bold"), # Bold legend title
    legend.text = element_text(size = 22,face = "bold"))+   # Bold legend text
    theme(strip.text.x = element_text(size=24, colour="Black", face="bold"))


dev.off()


```


```{r}

#####Show all the farms - those used antibiotics and those that did not- if they ever used or not for all cycles


cycle_antibUsed5_2<-merge(qamu_age,AMU1,by.x = c("coversheet.farm_barcode","Farm_cycle","production_cycles"),by.y = c("coversheet.farm_barcode","Farm_cycle","production_cycles"),all = TRUE)%>%
  arrange(indiv_flock.date_on_form)%>%
  mutate(med_usage.name_of_antibiotics=str_trim(med_usage.name_of_antibiotics))%>%
  mutate(med_usage.name_of_antibiotics=case_when(
    med_usage.name_of_antibiotics %in% c("agrar")~"Agrar_Agracox",
    med_usage.name_of_antibiotics %in% c("Amprosul")~"Agrar_Amprosul",
    med_usage.name_of_antibiotics %in% c("Agrar triple sulfa","Agrarian triple sulfa","Agrarian tripple sulfa","AgrarvTriple sulfa")~"agrar triple sulfa",
    med_usage.name_of_antibiotics %in% c("agraryl","Anglarry")~"Agraryl",
    med_usage.name_of_antibiotics== "aliseryl"~"Aliseryl ws",
    med_usage.name_of_antibiotics %in% c("Amidiostat","Amidiostat-Plus")~"Amidiostat-plus",
    med_usage.name_of_antibiotics %in% c("ampro_cox","Amprocox")~"Amprocox",
    med_usage.name_of_antibiotics %in% c("amprolium","Amprolium")~"Amprolium",
    med_usage.name_of_antibiotics %in% c("Bactofos","Bactofos plus","bactofos_plus")~"Bactofos plus",
    med_usage.name_of_antibiotics %in% c("biosol","Biosol","biosop")~"Biosol",
    med_usage.name_of_antibiotics %in% c("biotrim_vet")~"Biotrim-vet",
    med_usage.name_of_antibiotics %in% c("biotrim_vetplus")~"Biotrim-vet plus",
    med_usage.name_of_antibiotics == "Colistin 600"~"Colistin 600",
    med_usage.name_of_antibiotics =="colivet"~"Colivet",
    med_usage.name_of_antibiotics=="Dawa tylodoxy"~"Dawa-Tylodoxy 200",
    med_usage.name_of_antibiotics=="doxin_200"~"Doxin-200 ws",
    med_usage.name_of_antibiotics=="egocin"~"Egocin",
    med_usage.name_of_antibiotics=="enrocure"~"Enrocure",
    med_usage.name_of_antibiotics %in% c("Enronor","EnroNor")~"Enronor",
    med_usage.name_of_antibiotics=="Fluquin"~"Fluquin",
    med_usage.name_of_antibiotics=="Fosmit plus"~"Fosmit",
    med_usage.name_of_antibiotics=="limoxin"~"Limoxin ws",
    med_usage.name_of_antibiotics=="Meditrim"~"Meditrim WDP",
    med_usage.name_of_antibiotics=="miramid"~"Miramed",
    med_usage.name_of_antibiotics=="neoxy_vitamin"~"Neoxy-vitamin",
    med_usage.name_of_antibiotics %in% c("Not specified","Not_specified")~"Not specified",
    med_usage.name_of_antibiotics %in% c("oxymet","Oxymet","Oxymet-20","Oxymet 20","oxymet_20","Oxymet_20","oxymet_20%")~"Oxymet 20",
    med_usage.name_of_antibiotics=="super_skajcycline"~"Super skajcycline",
    med_usage.name_of_antibiotics %in% c("trimovet","Trimovet")~"Trimovet",
    med_usage.name_of_antibiotics %in% c("tylodoxi","tylodoxi200","Tylodoxin","tylosin")~"Tylodoxi 200",
    med_usage.name_of_antibiotics %in% c("veta_oxy20","vetoxy20")~"vetoxy 20",
      med_usage.name_of_antibiotics %in% c("Vitamet","vitamet chick","Vitamet chick")~"vitamet chick",
  TRUE~med_usage.name_of_antibiotics))%>%

  mutate(med_usage.amount_of_antibiotic_new=case_when(
    production_cycles==80 & med_usage.amount_of_antibiotic_new==5~10,
    production_cycles==93 & flock_t.flock_loop_group.number_doc==405 & med_usage.amount_of_antibiotic_new==1~0.5,
    TRUE~med_usage.amount_of_antibiotic_new))




```



```{r}


####Proportion of cycles antibiotics were used.

daily_drugbin9<-daily_drugbin4_A%>%
  dplyr::select(production_cycles,api_combination,antibiotic_class_combined)%>%
  distinct()%>%
group_by(api_combination,antibiotic_class_combined)%>%
  mutate(no_cycles=n())%>%
  mutate(prop_cycles=no_cycles/211*100)%>%
  ungroup()%>%
  dplyr::select(api_combination,antibiotic_class_combined,no_cycles,prop_cycles)%>%
    distinct()
  
  write.csv(daily_drugbin4,"daily4.csv")
  
  ggplot(daily_drugbin9, aes(x = reorder(api_combination, prop_cycles), y = prop_cycles, fill = antibiotic_class_combined)) +
  geom_col(position = "dodge") +
  theme_bw() +
  coord_flip() +
  theme(axis.text.y = element_text(angle = 0, hjust = 1)) +  # Because coord_flip
  scale_fill_manual(values = c(
    "Aminoglycosides, Tetracyclines" = "blue1",
    "Aminoglycosides, Tetracyclines, Polymixin, Macrolide" = "red1",
    "Fluoroquinolones" = "cyan1",
    "Sulfonamides, Macrolide, Diaminopyrimidine" = "darkmagenta",
    "Phosphonic, Macrolide" = "chocolate4",
    "Polymixin" = "deepskyblue",
    "Sulfonamides" = "violetred1",
    "Diaminopyrimidine, Sulfonamides" = "darkseagreen",
    "Tetracyclines" = "deepskyblue4",
    "Tetracyclines, Macrolide" = "green",
    "Tetracyclines, Polymixin" = "orange1"))+
    labs(x="Antibiotic combinations",y="Proportion of production cycles",fill="Antibiotic class")+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))+
      theme(
    axis.title = element_text(size = 14, face = "bold", colour = "black"),
    plot.title = element_text(size = 14,face = "bold"),
    axis.text = element_text(size = 14, face = "bold", color = "black", angle = 0),
    legend.title = element_text(size = 14,face = "bold"), # Bold legend title
    legend.text = element_text(size = 14,face = "bold"))+   # Bold legend text
    theme(strip.text.x = element_text(size=14, colour="Black", face="bold"))
  

  ###complex upset
  
#prepare data for complex upset graphs
  
  
  ###create wide data
 
  complex <- daily_drugbin4 %>%
    dplyr::mutate(present=1)%>%
  distinct(production_cycles,api_combination,antibiotic_class_combined,api_name,.keep_all = TRUE)%>%
    pivot_wider(
      names_from = api_name,
      values_from = present,
      values_fill = 0
    )
    

  
  write.csv(complex,"complex_analy.csv")


###create antibiotic lookup
antibiotics=colnames(complex[4:17])
antibiotics


complex[antibiotics]=complex[antibiotics]==1

t(head(complex[antibiotics],3))

###Utility for changing output parameters in Jupyter notebooks (IRKernel kernel)
  
   set_size=function(w,h,factor=2.5){
    s=1*factor
    options(
        repr.plot.width=w * s,
         repr.plot.height=h * s,
         repr.plot.res=100 / factor,
         jupyter.plot_mimetypes='image/png',
         jupyter.plot_scale=1
     )
    
    }
 
  set_size(w = 14, h = 16)  # Increase height here (e.g., h = 10 or more)
###plot the complex upset graph

upset(complex,antibiotics,name = "antibiotics",width_ratio = 0.1)


set_size(8, 3)


upset(
  complex,
  antibiotics,
  name = "Antibiotic combinations",
  width_ratio = 0.5,
  height_ratio = 1.2,
  ##stripes = c('', ''),

  themes = upset_modify_themes(
    list(
      'intersections_matrix' = theme(text = element_text(size = 26, face = "bold",colour = "darkred")),
      "set_names" = theme(
      axis.text.y = element_text(size = 26, face = "bold",colour = "black"),  # List of antibiotics (set names)
      axis.title.y = element_blank()
    )
  )),

  set_sizes=upset_set_size(geom = geom_bar( width = 0.8, fill = "steelblue"),position = 'right')
        + scale_y_continuous(
          
           labels = function(x) paste0(round((x / 211) * 100))
           
          
        )
        + ylab('Proportion of cycles')+
  theme(
      axis.text.x = element_text(angle = 0, size = 24, face = "bold"),
      axis.title = element_text(size = 24, face = "bold",colour = "darkred"),
      axis.title.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank()
    ),
    
  base_annotations = list(
  'Intersection size' = intersection_size(
    aes(shape = antibiotic_class_combined),
    counts = FALSE
  ) +
    geom_col(fill = "steelblue", width = 0.8) + 
    geom_point(size = 4, stroke = 2.0) +      # replace bars with points
    scale_shape_manual(values = c(            # manually define up to 25 shapes
      "Aminoglycosides, Tetracyclines" = 0,
      "Aminoglycosides, Tetracyclines, Polymixin, Macrolide" = 1,
      "Diaminopyrimidine, Sulfonamides" = 2,
      "Fluoroquinolones" = 3,
      "Phosphonic, Macrolide" = 4,
      "Polymixin" = 5,
      "Sulfonamides" = 6,
      "Sulfonamides, Macrolide, Diaminopyrimidine" = 17,
      "Tetracyclines" = 8,
      "Tetracyclines, Macrolide" = 9,
      "Tetracyclines, Polymixin" = 20
    )) +
  scale_y_continuous(

          labels = function(y) paste0(round((y / 211) * 100)))+
         
    labs(
      x = "Intersection (Antibiotic combinations)",
      y = "Proportion of production cycles",
      shape = "Antibiotic class combination"
    ) +
   
    
    theme(
      text = element_text(size = 20, face = "bold"),
      axis.title.y = element_text(size = 20, face = "bold", colour = "darkred"),
      axis.title.x = element_blank(),
      axis.text.y = element_text(size = 20, face = "bold"),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      legend.title = element_text(size = 22, face = "bold", colour = "darkred"),
      legend.text = element_text(size = 20, face = "bold"),
      legend.position = "right",
      legend.direction = "vertical",
      legend.justification = "top"
    )
),

  guides = "over"
)


  
```

